### ISSUE TITLE
Release version

### ISSUE THREAD

**Issue by Tsjunne** [rebus-org/Rebus.Microsoft.Extensions.Logging#1]
Is there a plan to publish a release version of this library?
If not, what would be the preferred way to hook into the default netcore abstractions?

**Comment by mookid8000** [comment]
> Is there a plan to publish a release version of this library?

Have you tried it? If you believe it works as it should, I can release a non-prerelease version.

> If not, what would be the preferred way to hook into the default netcore abstractions?

I don't understand this question 🤔 ❓ is is because you can't use a prerelease library?

**Comment by Tsjunne** [comment]
> I don't understand this question 🤔 ❓ is is because you can't use a prerelease library?

I just thought that maybe it was abandoned.

But, yes, it seems to work just fine for me, so a release version of the package would be nice, since we try to keep prerelease packages out of production

**Comment by mookid8000** [comment]
I've pushed Rebus.Microsoft.Extensions.Logging 1.0.0 – it's on Nuget.org as soon as their indexing wakes up 😉 thanks for reminding me to do this! 👍

**Comment by Tsjunne** [comment]
Tops! Thx!
