### ISSUE TITLE
How to set log levels?

### ISSUE THREAD

**Issue by woeterman94** [rebus-org/Rebus.Microsoft.Extensions.Logging#12]
Is there any way I can configure the log levels? I don't want my application insights to be flooded with trace messages.

![image](https://github.com/rebus-org/Rebus.Microsoft.Extensions.Logging/assets/5755057/bd17071d-0c4d-461f-a170-81416822009f)

**Comment by mookid8000** [comment]
When you use Rebus.Microsoft.Extensions.Logging, it just makes Rebus pipe its logs to Microsoft.Extensions.Logging, so you'll need to find out how to configure (and possibly filter) logs with Microsoft.Extensions.Logging.

I almost always use Serilog, so unfortunately I cannot help you 😉
