### ISSUE TITLE
Microsoft.Extensions.Logging v2.2?

### ISSUE THREAD

**Issue by KatoStoelen** [rebus-org/Rebus.Microsoft.Extensions.Logging#2]
Is there a reason why this project is referencing version `2.2.0` of `Microsoft.Extensions.Logging`? Since .NET Core 2.1 is the current LTS version (until 3.1 is released), I assume other development teams out there have the same restrictions as us, where the 2.2 runtime is not installed on production servers.

Even though it *might* work referencing this project from an application using target framework `netcoreapp2.1`, I'd feel safer if this project were using version `2.1` (or even `2.0`) of `Microsoft.Extensions.Logging`. Does not seem like this project requires any specific features of version `2.2.0`?

**Comment by mookid8000** [comment]
I'm pretty sure it doesn't require 2.2.0 in any way.

PR?
