### ISSUE TITLE
net6 support for Rebus.Microsoft.Extensions.Logging

### ISSUE THREAD

**Issue by dannythunder** [rebus-org/Rebus.Microsoft.Extensions.Logging#9]
Got conflicts when using 

Add support for net6 in Rebus.Microsoft.Extensions.Logging. 
Add support for Microsoft.Extensions.Logging v6 (low) in Rebus.Microsoft.Extensions.Logging

PR:
[Pull req](https://github.com/rebus-org/Rebus.Microsoft.Extensions.Logging/pull/7)

**Comment by mookid8000** [comment]
Cool cool, but what do you accomplish by adding .NET Standard 2.1, .NET 5, and .NET 6 as additional targets?

What do you mean by "got conflicts when using"?

**Comment by dannythunder** [comment]
@mookid8000  I redid the PR. The first was based on the 3.0.0 branch, redid it and based it on master.

Thats why there was additional targets.

conflicts as in warnings, my bad.


A bit late... 🙄

**Comment by mookid8000** [comment]
It still looks like the Rebus.Microsoft.Extensions.Logging project is targeting .NET 6.

Could you make it .NET Standard 2.0 instead?

**Comment by dannythunder** [comment]
Fixed

**Comment by dannythunder** [comment]
@mookid8000 I see that the code is in master, but I cant't see a new nuget for this. Do you have to trigger it manually? And this issue can be closed after the nuget package is created.

**Comment by mookid8000** [comment]
Oh, damn! And yes, the release process is something that needs to be manually triggered.

I did it now though 🙂 with some other changes that seemed necessary - let me know if it works as it should!
